PIA.DotNet.Interview.WebUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PIA.DotNet.Interview.WebUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PIA.DotNet.Interview.WebUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Server.IIS.Core;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PIA.DotNet.Interview.Core.Models;
using PIA.DotNet.Interview.WebUI.UI_BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace PIA.DotNet.Interview.WebUI.Pages
{
    public class IndexModel : PageModel
    {

        private readonly ILogger<IndexModel> _logger;

        public IConfiguration Configuration { get; private set; }

        private string _remoteServiceBaseUrl = ""; // as default value

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            //Configuration
            var builder = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);

            Configuration = builder.Build();

            _remoteServiceBaseUrl = Configuration.GetSection("AppSettings").GetValue<string>("WebserviceHostName");
        }

        public void OnGet()
        {
            _logger.LogInformation("Data was loaded on the page");
        }

        public  IActionResult OnPostSubmit(string id)
        {
            var data = id;

            _logger.LogInformation(String.Format("Task  with ID - {0} was finished", id));
            TaskService taskService = new TaskService(_remoteServiceBaseUrl);
            TaskViewModel taskViewModel = taskService.Get(id).Result;
            if (taskViewModel != null)
            {
                taskViewModel.IsFinished = true;
            }

            var result =taskService.Edit(id,taskViewModel);
            _logger.LogInformation("Task changes  - Data was saved in to DB");
            return RedirectToPage("/Index");


        }
        public  IActionResult OnPostDelete(string id)
        {
            var data = id;
            _logger.LogInformation(String.Format("Task  with ID - {0}  will  be deleted", id));
            TaskService taskService =  new TaskService(_remoteServiceBaseUrl);
            TaskViewModel taskViewModel = taskService.Get(id).Result;
            var result = taskService.Delete(id, taskViewModel);
            _logger.LogInformation("Task changes  - Data was deleted from to DB");

            return RedirectToPage("/Index");

        }

    }
}

PIA.DotNet.Interview.WebUI/Pages/Readme.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PIA.DotNet.Interview.WebUI.Pages
{
    public class ReadmeModel : PageModel
    {
        private readonly ILogger<ReadmeModel> _logger;

        public ReadmeModel(ILogger<ReadmeModel> logger)
        {
            _logger = logger;
        }
        public void OnGet()
        {
            _logger.LogInformation("Data was loaded on the page Readme");
        }
    }
}

PIA.DotNet.Interview.WebUI/Pages/Statistik.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Web;

namespace PIA.DotNet.Interview.WebUI.Pages
{
    public class StatistikModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PIA.DotNet.Interview.WebUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@using UI_BL
@inject TaskService _taskService

<div class="text-left">
    <h1 class="alert-success text-center">Tasks</h1>
    <h3>The tasks for this interview sample are as follows:</h3>

    @foreach (var task in await _taskService.Get())
    {
        <div class="card mb-3 @(task.IsFinished ? "text-white bg-primary" : "bg-light")">
            <div class="card-header">
                Task @task.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@task.Title</h5>
                <p class="card-text">@Html.Raw(task.Description)</p>
                @if (!String.IsNullOrWhiteSpace(task.Example))
                {
                    <div class="card" style="width:400px">
                        <img class="card-img-top" src="@Html.Raw(task.Example)" alt="Card image" style="width:100%">
                        <div class="card-footer">
                            <small class="text-muted">Example</small>
                        </div>
                    </div>
                }

                <form method="post" >
                    <button class="btn btn-primary mt-1" asp-route-id="@task.Id" asp-page-handler="Submit">Erledigt</button>
                    <button class="btn btn-primary mt-1" asp-route-id="@task.Id" asp-page-handler="Delete">Löschen</button>
                </form>

                @if (task.IsFinished)
                {
                    <div class="alert-success" >
                        <p class="card-text" style="font-weight:bold;display: inline">Erledigt! </p><p class="card-text" style="display: inline">Die Aufgabe wurde erledigt</p>
                        
                    </div>
                }


            </div>
        </div>
    }

</div>

PIA.DotNet.Interview.WebUI/Pages/Readme.cshtml
@page
@model PIA.DotNet.Interview.WebUI.Pages.ReadmeModel
@{
    ViewData["Title"] = "Readme page";
}
@using UI_BL
@inject MarkdownService _markdownService

<div>
    @Html.Raw(@_markdownService.Parse(@"C:/Source/README.md"));
</div>

PIA.DotNet.Interview.WebUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PIA.DotNet.Interview.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PIA.DotNet.Interview</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Readme">Readme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Statistik">Statistik</a>
                        </li>
                        @* here----- *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PIA.DotNet.Interview - <a href="https://www.piagroup.com/">PIA Homepage</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

PIA.DotNet.Interview.WebUI/Pages/Statistik.cshtml
@page
@model StatistikModel
@{
    ViewData["Title"] = "Statistik";
}
@using UI_BL
@using System.Linq
@inject TaskService _taskService
@{
    var tasks = _taskService.Get().Result;
    var done = tasks.Count(t => t.IsFinished);
    var notDone = tasks.Count(t => !t.IsFinished);
    var result = new int[] { done, notDone };
}
<div class="text-left">
    <h1 class="alert-success text-center">PIA.DotNet.Interview - Erledigte Aufgaben</h1>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <canvas id="StatistikChart"></canvas>
    <script>
                        var ctx = document.getElementById('StatistikChart');
                        var chart = new Chart(ctx, {
                        type: 'pie',
                        data:
                        {
                        labels: ['Done', 'NotDone'],
                        datasets:
                                [{
                                label: '',
                                data:@Html.Raw(Json.Serialize(result)),
                                backgroundColor:['rgb(255, 99, 132)','rgb(54, 162, 235)'],
                                hoverOffset: 4
						        }]
                    }
                });
	    </script>
    @{

    }

</div>